# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_ID: "217264062244663"
FACEBOOK_SECRET_KEY: "a40e8d6c9c6454eeed8a50d0eca5d22c"
TWITTER_APP_ID: "BA0IcYVQW6lM54NZVqqNFjimi"
TWITTER_SECRET_KEY: "utKiBl16WUnC2mt79tgxVPGT6x2UZGQaoASf4iRYkGVB3aqx2T"
ADMIN_EMAIL: "admin@getotato.com"
ADMIN_PASS: "Abrahamlovesadmin"
RAILS_SERVE_STATIC_FILES: "true"
DEVISE_SECRET_KEY: "d538bd59912d2854b5dac055b350b0538d152536048c1cd5bbf8f7c4e4fbf9e6a7887c196675fb3506d789683261f4557602b3637ef006bbf06ee22787b387d1"
SECRET_KEY_BASE: "ddec2a531a8c51e8b174b4605f7b6fbdcc33c86b5be08259bfd7c3e9847cef106892ab8a44861e66289067aebfc4a232a54a4cb6f22f082ff30b972878db8865"
SES_SMTP_PASSWORD: "AkCiDGFkp5WHjwBUmPejt/x+IDz8dFzo7bXMbyDdAhfs"
SES_SMTP_USERNAME: "AKIAIGTWTPF2G4RJJEKA"
